import * as esbuild from 'esbuild';
import * as path from 'node:path';
import * as fs from 'node:fs/promises';
import { ensureDir } from '../utils/fs.js';
import { logger } from '../utils/logger.js';
import type { ProjectConfig } from './config.js';

export interface CompileOptions {
	target: 'html5';
	minify: boolean;
	sourcemap: boolean;
	watch: boolean;
	analyze: boolean;
}

export async function compile(config: ProjectConfig, options: CompileOptions): Promise<void> {
	const outDir = path.resolve(config.output.dir);
	await ensureDir(outDir);

	const esTarget = 'es2022';
	const format = 'esm';
	const platform = 'browser';

	const define: Record<string, string> = {
		'process.env.DEBUG': JSON.stringify(!options.minify),
		'process.env.RELEASE': JSON.stringify(options.minify),
	};

	const commonOptions: esbuild.BuildOptions = {
		sourcemap: options.sourcemap,
		target: esTarget,
		format,
		platform,
		define,
		logLevel: 'warning' as const,
		metafile: options.analyze,
	};

	if (options.minify) {
		// Release mode: multi-entry + code splitting
		const entryPoints: Record<string, string> = {};

		// Main game entry
		entryPoints['main'] = path.resolve(config.entry);

		// Skin entry (if generated by bundle policy)
		const skinIndex = path.resolve('src/_generated/skins/index.ts');
		try {
			await fs.access(skinIndex);
			entryPoints['default.thm'] = skinIndex;
		} catch {
			// No generated skins, skip
		}

		// Engine entry: a stub that imports vendor packages so esbuild splits them into a shared chunk
		const engineStub = genEngineStub(config);
		const engineStubPath = path.resolve('src/_generated/engine.ts');
		await ensureDir(path.dirname(engineStubPath));
		await fs.writeFile(engineStubPath, engineStub);
		entryPoints['blakron.engine'] = engineStubPath;

		const buildOptions: esbuild.BuildOptions = {
			...commonOptions,
			entryPoints,
			outdir: outDir,
			bundle: true,
			minify: true,
			splitting: true,
			entryNames: '[name]',
			chunkNames: 'chunks/[name]-[hash]',
		};

		if (options.watch) {
			const ctx = await esbuild.context(buildOptions);
			await ctx.watch();
			logger.info('Watch mode active (minify). Press Ctrl+C to stop.');
			await new Promise<void>(resolve => {
				const handler = async () => {
					process.off('SIGINT', handler);
					await ctx.dispose();
					resolve();
				};
				process.on('SIGINT', handler);
			});
		} else {
			const result = await esbuild.build(buildOptions);

			if (options.analyze && result.metafile) {
				const analysis = await esbuild.analyzeMetafile(result.metafile);
				logger.info('Bundle size analysis:\n' + analysis);
			}
		}
	} else {
		// Dev mode: bundle without minification
		const buildOptions: esbuild.BuildOptions = {
			...commonOptions,
			entryPoints: [path.resolve(config.entry)],
			outfile: path.join(outDir, 'main.js'),
			bundle: true,
			minify: false,
		};

		if (options.watch) {
			const ctx = await esbuild.context(buildOptions);
			await ctx.watch();
			logger.info('Watch mode active. Press Ctrl+C to stop.');
			await new Promise<void>(resolve => {
				const handler = async () => {
					process.off('SIGINT', handler);
					await ctx.dispose();
					resolve();
				};
				process.on('SIGINT', handler);
			});
		} else {
			const result = await esbuild.build(buildOptions);

			if (options.analyze && result.metafile) {
				const analysis = await esbuild.analyzeMetafile(result.metafile);
				logger.info('Bundle size analysis:\n' + analysis);
			}
		}
	}
}

function genEngineStub(config: ProjectConfig): string {
	// Collect vendor packages from dependencies
	const vendors = ['@blakron/core', '@blakron/ui', '@blakron/game'];
	return [
		'// Auto-generated engine entry — imports vendor packages for code splitting',
		...vendors.map(pkg => `import '${pkg}';`),
		'',
	].join('\n');
}
